### ISSUE TITLE
Should be arguments quoting optional?

### ISSUE THREAD

**Issue by RolandTaverner** [klemens-morgenstern/boost-process#123]
Hi!
I have an issue with automatic arguments quoting. Here is the situation.
```
void generateArgs(std::vector<std::string> &args)
{
 // this happens in a galaxy far, far away so I don't know what really can be here
  args.push_back("-f /path/to/file");
  args.push_back("--PID 42");
  args.push_back("--some_option");
}

void run()
{
  std::vector<std::string> args;
  generateArgs(args);
  bp::child child(bp::exe = "program.exe", bp::args = args);
// Oops we got 
// program.exe "-f /path/to/file" "--PID 42" --some_option
// instead of
// program.exe -f /path/to/file --PID 42 --some_option
}
```
I think it would be nice to have an option to disable automatic quoting.

**Comment by klemens-morgenstern** [comment]
Well the cmd style should do that:

```
void generateArgs(std::string & cmd)
{
 // this happens in a galaxy far, far away so I don't know what really can be here
  cmd += " -f /path/to/file";
  cmd += " --PID 42";
  cmd += " --some_option";
}

void run()
{
  std::string cmd = "program.exe"
  generateArgs(cmd);
  bp::child child(cmd);
}
```

Does that solve it?

**Comment by RolandTaverner** [comment]
Thank you for the reply.

Cmd style also not working - it throws "CreateProcess failed: The system cannot find the path specified." It seems to me that it is a bug - executor::operator()(){} calls `CreateProcess("", "program.exe ...", ...)` instead of `CreateProcess(NULL, "program.exe ...", ...)`.
`bp::child(bp::args = "c:\\Windows\\System32\\cmd.exe")` fails but `bp::child(bp::exe = "c:\\Windows\\System32\\cmd.exe")` works.
Anyway I prefer to use CreateProcess("module", "args") form whenever possible because I don't like behavior details of CreateProcess(NULL,...). Besides that I think  `child(bp::exe = "program.exe", bp::args = args)` is more natural and expressive.

**Comment by RolandTaverner** [comment]
Sorry, accidentally closed the issue.

**Comment by klemens-morgenstern** [comment]
Well the problem is the underlying implementation; the args on posix are not a single string, but a an array of strings. That means, they have to be tokenized, and thus "foo", "foo bar" get passed as such. That is then implemented with quoting on windows, to keep it consistent. So I wouldn't feel good about splitting that, and would consider such a feature unneeded, since you could also just use `bp::args+={"foo", "bar"} or
 [`boost::split`](http://www.boost.org/doc/libs/1_65_1/doc/html/string_algo/reference.html#header.boost.algorithm.string.split_hpp) to do that.

FYI: `bp::child(bp::cmd="c:\\Windows\\System32\\cmd.exe")` also works.

**Comment by RolandTaverner** [comment]
Thank you. Understood your point.
