### ISSUE TITLE
C++11 required?

### ISSUE THREAD

**Issue by aaronovz1** [klemens-morgenstern/boost-process#17]
Is C++11 required? I was seeing errors which suggested I needed to compiler set to c++11

**Comment by klemens-morgenstern** [comment]
Yes. Including the <future> header.

**Comment by aaronovz1** [comment]
Not possible to use boost to get around needing c++11 natively?

**Comment by klemens-morgenstern** [comment]
Not with the design I chose. I already went down from C++14, that was painful enough.

It would probably be possible to do a similar library in C++98, but I would have to rewrite the whole thing. I'm sorry, but I don't think it's a good decision to use deprecated standards for new libraries, if the workarounds are not trivial.

**Comment by klemens-morgenstern** [comment]
Oh btw: if you want to have similar library, just use the [older version](https://github.com/BorisSchaeling/boost-process).

If you have issues there or want to make a C++98 fork, I'll help you - or at least I explain how I solved it.

Why do you need C++98? Ancient compiler at work?

**Comment by aaronovz1** [comment]
Thanks. Yes compiler limitations at work. I will be moving to new compiler in new product but older product we still support is locked in. The reason I found this version of Boost process was because of needing timeout functionality which is not available in 0.5. I hacked up a simple modification of wait_for_exit which allows a timeout to be specified but it's not perfect. There also seems to be some quirky things in 0.5 I was hoping would be easier or resolved in 0.6.

**Comment by klemens-morgenstern** [comment]
Well it is, but the developer chose to make it easier for himself. Yeah, the `wait_for_exit` thing is rather easy, you can basically copy and paste this from my code [windows](https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/wait_for_exit.hpp)
and [posix](https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/posix/wait_for_exit.hpp)
In 0.5. the pid/handle is just a member of the child class, so that's very easy to obtain.

I do however recommend to use boost.asio for that stuff, though using named pipes is a bit more complicated with 0.5.
