### ISSUE TITLE
Add further examples on async IO?

### ISSUE THREAD

**Issue by emmenlau** [klemens-morgenstern/boost-process#175]
The async IO fuctionality of boost-process is an awesome feature. However I find it a bit hard to get started, and there are very few examples on the internet. Would it be possible to add a more complex example for async IO?

Very specifically, I could not find any examples how to implement a non-blocking read from the process output. I would like to query in regular intervalls for new content on childs stdout and stderr, but not block if there is no new content. However there is no peek(). I would be able to implement this the hard way with blocking reads from additional threads and synchronization, but most likely boost::asio can make this simpler? An example to get started would be great!

**Comment by klemens-morgenstern** [comment]
I hear you, the problem is that this is mainly providing functionality done with boost.asio. If I were to explain all the features of that (e.g. how you can use coroutines) I'd be duplicating the asio documentation. And the possibilities are just to manyfold to give a short starting example.

So sry I can't write you a full example, I can give you a few pointers though: build on thread that runs an [io_context](https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/io_context.html) and you can than put a [timer](https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/deadline_timer.html) in there.
Now, you call `.async_read_some`. on both pipes and once the funicton completes you put whatever you've read into a buffer, which is checked by the timer and call `async_read_some` again. If you use the `io_context` just from one thread or use an [io_context::strand](https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/io_context__strand.html) you don't need to worry about synchronization between the timer and the read-completion handlers.
Hope that made a bit of sense, if not look at the socket-examples of asio, that's how you can use the `async_pipe`.

**Comment by emmenlau** [comment]
Ok I agree that the request is a bit specific. I will try to follow your answer and post back a working implementation here when I have one. Thanks a lot for the great work!

**Comment by klemens-morgenstern** [comment]
It's not even the request, it's just the our tools are so powerful that you have a lot of possibilites. If you need more help feel free to send me an e-mail.
