### ISSUE TITLE
msvc 2015 warnings

### ISSUE THREAD

**Issue by frederich** [klemens-morgenstern/boost-process#26]
The code below doesn't compile with the newest winapi modules and /WX

`
boost::process::child c("c:/windows/system32/foo.exe", "/r", dll);
c.wait();
`

Visual Studio 2015
64-bit debug build
boost 1.62.0 static build, with static runtime
flags: /WX /W4 
pp: _SCL_SECURE_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;

`
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'argument': conversion from '__int64' to 'int', possible loss of data	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\locale.hpp	49	
Warning	C4244	'argument': conversion from '__int64' to 'int', possible loss of data	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\locale.hpp	71	
Warning	C4800	'boost::detail::winapi::BOOL_': forcing value to bool 'true' or 'false' (performance warning)	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\child_handle.hpp	85	
Warning	C4800	'boost::detail::winapi::BOOL_': forcing value to bool 'true' or 'false' (performance warning)	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\child_handle.hpp	92	
Warning	C4800	'boost::detail::winapi::BOOL_': forcing value to bool 'true' or 'false' (performance warning)	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\group_handle.hpp	146	
Warning	C4800	'boost::detail::winapi::BOOL_': forcing value to bool 'true' or 'false' (performance warning)	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\group_handle.hpp	153	
Warning	C4800	'boost::detail::winapi::BOOL_': forcing value to bool 'true' or 'false' (performance warning)	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\group_handle.hpp	183	
Warning	C4099	'boost::process::detail::windows::group_handle': type name first seen using 'struct' now seen using 'class'	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\wait_group.hpp	16	
Warning	C4100	'state': unreferenced formal parameter	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\locale.hpp	38	
Warning	C4100	'state': unreferenced formal parameter	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\locale.hpp	60	
d:\src\trunk\third_party\boost\include\boost\fusion\container\generation\detail\preprocessed\make_set10.hpp	35	
Warning	C4459	declaration of 'env' hides global declaration	fpreg	D:\src\trunk\third_party\boost\include\boost\process\environment.hpp	57	
Warning	C4458	declaration of 'ios' hides class member	fpreg	D:\src\trunk\third_party\boost\include\boost\process\async.hpp	59	
Warning	C4459	declaration of 'on_error' hides global declaration	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\executor.hpp	183	
Warning	C4459	declaration of 'on_error' hides global declaration	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\executor.hpp	215	
Warning	C4459	declaration of 'on_setup' hides global declaration	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\executor.hpp	178	
Warning	C4459	declaration of 'on_success' hides global declaration	fpreg	D:\src\trunk\third_party\boost\include\boost\process\detail\windows\executor.hpp	206

**Comment by klemens-morgenstern** [comment]
Well for the original question:  I found another missing function in the WinApi and merged it after 1.62, so you need to checkout the latest version of [boost/winapi](https://github.com/boostorg/winapi) into your boost folder.

But it seems you figured that out. Now for this compile error, I do have to see the actual error description, because I only see warnings. Or do you have a runtime-error?

**Comment by frederich** [comment]
Yes, I've runtime errors. In our company all warnings are treat as errors, compiler switch /WX. Please tidy up all warning, otherwise I cannot use boost.process.

**Comment by klemens-morgenstern** [comment]
First of all: can I get a description of the runtime-error? It does really help a develop to know what is going wrong.

Secondly: ain't gonna happen, especially since I don't know what fpreg is. I never got this message. 
Also: I really don't see the point in setting warnings as error, if they have well-defined behaviour , e.g. `bool foo() {return 42;}`. That sort of thing happens when you interact with the WinApi and I don't think there's a write code which doesn't emit any warnings - especially since it depends on other boost libraries 

So feel free to create a PR for that, which I will accept if it doesn't break anything and isn't only msvc extensions.

**Comment by frederich** [comment]
No, other boost libraries don't produce warnings, sorry. At the moment it's boost.process only, and I have many others in use.

It's a company decision not my personal. Simple statement: fix your warnings, nothing more nothing less. There are many ways to fix does warnings, for instance, boost::ignore_unused, right cast operators or disable some stupid warnings with #pragma. When you want that boost.process will use in production code, please remove all warning issues. I cannot switch off /WX; is forbidden. I use the native Windows API as a workaround, but I like boost.process you do excellent job, and I want to use it in production code.

[fpreg_warnings.txt](https://github.com/klemens-morgenstern/boost-process/files/538667/fpreg_warnings.txt)

**Comment by klemens-morgenstern** [comment]
Thanks for the actual compiler output, precise error reports do in fact help.

Now to clarify my point of view: it makes a lot of sense for a header-only library to minimize the amount of warnings generated. And there's room for improvement here, though it's not high on my priority list. You can of course accelerate that by providing a PR which I'll gladly accept.
It will however not be possible to provide you a warning free library, since I will neither put a plain "#pragma" into the code (which will generate a warning on another compiler) nor will I allow any performance hit.

I do think, that warning-as-error is a bad policy, especially with stupid warnings like C4458 or worse C4459.
There are in fact other boost libraries generating warnings. I've built it often enough to know, for example, gcc will always generate this warning when including `boost.asio`:

```cpp
../../../boost/asio/error.hpp:258:45: warning: ‘boost::asio::error::system_category’ defined but not used [-Wunused-variable]
 static const boost::system::error_category& system_category
```

There are just things the compiler complains about, but it's not bad, not an error, not a sign of bad code. Having no warnings is no sign of good code, having them not a sign of bad code. I feel for you, when you have this policy at work, but please understand why it's not as important for me as it is for you.
