### ISSUE TITLE
Compile errors when instanciating a child process

### ISSUE THREAD

**Issue by HeinrichGit** [klemens-morgenstern/boost-process#40]
This issue was closed once with #21, however, I have the same problem now... g++5.4 / boost 1.56 / system;filesystem Boost 1.53.0

**Comment by klemens-morgenstern** [comment]
It depends on boost 1.63 as stated in the readme.

**Comment by HeinrichGit** [comment]
Is this ok, to be that dependent on a certain version?

**Comment by klemens-morgenstern** [comment]
Why wouldn't it be? I want this library to be part of boost, so it will hopefully be released with boost in a future version.
You can get it from [github](https://github.com/boostorg/boost)
Basically you need the newest [winapi](https://github.com/boostorg/winapi) module in order to build on windows (you can also take 1.62 and overwrite the module) and you need a newer version of fusion. At least your's is too old, I'm not sure which one fixes the move problem, I'm guessing 1.60 or maybe 1.58. But however that may be: you need a newer version, just try 1.62.
