### ISSUE TITLE
boost 1.63 dependency

### ISSUE THREAD

**Issue by MattyBoy4444** [klemens-morgenstern/boost-process#42]
Just a question.  Does this REALLY have to use some of the latest developments in 1.63?  Sure would be nice if we could stay boost 1.62 compatible.  I would like to just use boost-all-dev package from Ubuntu.

**Comment by klemens-morgenstern** [comment]
The dependency on boost 1.63 is necessary on windows because I added code to boost/winapi which will only be in 1.63. On posix it should be compatible with 1.62, I guess even down to ~1.59, where some fix to boost.fusion was made. So just see if it works, if you need a workaround and develop one, let me know.
But since it is absolutely necessary to have 1.63 as a dependency on windows, I'm not very motivated to work on a backwards compatibility; additionally, I'm happy to report, that the library has been accepted, so it will hopefully be in boost 1.64.
