### ISSUE TITLE
Is there some way to ensure that the child is terminated when the parent dies?

### ISSUE THREAD

**Issue by henriksjostrom** [klemens-morgenstern/boost-process#66]
Is there some way to ensure that the child is terminated when the parent dies?

I have a process that shouldn't be left running after my main program dies. My first solution has been to wrap the child in a class that calls terminate in the destructor but this is insufficient as they aren't called on abnormal exit.

**Comment by klemens-morgenstern** [comment]
Afaik not directly, no. It implements your first approach, i.e. the destructor of [child](http://klemens-morgenstern.github.io/process/boost/process/child.html) terminates if not detached.

Now you can [group](http://klemens-morgenstern.github.io/process/process/reference.html#header.boost.process.group_hpp) child processes together, but that's rather limited for the launching process (you find the used implementation referenced there). And from what I remember from my research, this is because the OS does not provide proper facilities for that, i.e. I'd need them on both windows and posix.
If you however find a solution to do that, I'll gladly add it to the library.

**Comment by henriksjostrom** [comment]
I have 2 solutions neither entirely optimal.

1. (The one I'm using in my own code) To register terminate on std::at_quick_exit & std::atexit. Wont help with sigkill but works for sigint as far as I have been able to determine. Not really optimal for a library like this to make use of however one such reason being that the number of functions one can register for this is somewhat limited in addition to not being a very pretty solution in general.

2. Creating a monitoring process with the goal of shutting down the process if the parent dies and then suicide. This obviously has the overhead of creating yet another process

**Comment by klemens-morgenstern** [comment]
Yeah, that's how I remembered that, thus my library doesn't help. Well I mean you can use `child::terminate` from `std::atexit`.
As for the second, yes that has some overhead, but you can use groups to make this a bit easier.
