### ISSUE TITLE
extension handlers different values in Executor's error_code for on_success

### ISSUE THREAD

**Issue by pvanek** [klemens-morgenstern/boost-process#81]
on Posix error_code contains value = 0, category = "system", but message differs

Linux: "Success"
OS X: "Undefined error: 0"

is it expected behavior (getting these strings from system)?

**Comment by klemens-morgenstern** [comment]
That's getting the errors from the system, is no error posix. This also would be an error in the C++ system, since that is a part of the [STL](http://en.cppreference.com/w/cpp/error/error_code). You should go with `operator bool` i.e.:
```
std::error_code ec = foo();
if (ec)
{
   //handle error
}
```

and for more details use [errc](http://en.cppreference.com/w/cpp/error/errc).
